### ISSUE TITLE
The modified image display is not working in the admin ui of Wagtail 4.0.1 and Django 4.1.1

### ISSUE THREAD

**Issue by ChefdeCambuse** [donhauser/wagtail-photo-gallery#6]
![Screenshot (564)](https://user-images.githubusercontent.com/100775/190382013-52d2a6f9-4e79-44c1-9a6c-496323cc07d3.png)

**Comment by donhauser** [comment]
Hi, thank you very much for your report!

The admin panel UI in Wagtail 4.0 has changed a lot in comparison to previous versions like Wagtail 2.16.
Due to this changes the CSS and HTML code (which is pretty "hacky" here) is currently incompatible.

I will create a fixed version during the next weeks 👍

**Comment by donhauser** [comment]
This is now fixed in version 0.1.0
